### ISSUE TITLE
How to validate an address had submit a sealed bid?

### ISSUE THREAD

**Issue by aihunter666** [maurelian/dot-eth-js#31]
hello.
I have a question in the reveal period of the auction.
How to validate an address had submit a sealed bid?

**Comment by maurelian** [comment]
There's no simple way to do that built into either the ENS contracts, or this library. 

You would need to look at which addresses have sent a message to the Registrar contract. Any address that has submitted a call with the data starting in `ce92dced` which is the function ID for `newBid(bytes32)` would have submitted a sealed bid.
